### ISSUE TITLE
After the Youtube changed their transcript format..

### ISSUE THREAD

**Issue by soyant** [dobladov/youtube2Anki#18]
After the Youtube changed their transcript format..
this wonderful Youtube2anki doesn't work.
with this message....  "transcript not found"

I'd appreciate it if you could take a moment to fix this problem.

![youtube transcript format changed](https://user-images.githubusercontent.com/61927051/155823604-9b4d8931-1d81-4548-8e6f-415ff17de6c1.JPG)

**Comment by dobladov** [comment]
The problem was due to some changes in [how the title is obtained](https://github.com/dobladov/youtube2Anki/commit/7de45b74cf30ebd39fe18614556fa46d041be588). 

I already made a fix and submitted the new version to the chrome store, version `1.0.1` it should be ready as soon as it is reviewed.

Thanks for reporting and for your encouraging words about the extension @soyant

**Comment by soyant** [comment]
Always thank you!

**Comment by dobladov** [comment]
It's live now, let me know if you still encounter any problems.
