### ISSUE TITLE
Feature request: trim youtube video to time rather than transcript sentences

### ISSUE THREAD

**Issue by ghost** [dobladov/youtube2Anki#9]

**Comment by dobladov** [comment]
If I understand correctly you mean to cut the videos in chunks and download them?

In that case I don't think this extension is the right one to do it, since I wanted to keep the data download as minimum as possible, in that case I recommend to use this tool. https://github.com/emk/subtitles-rs/blob/master/substudy/README.md; It will cut any downloaded video based on the subtitles, in the case of YouTube you can download the videos with https://ytdl-org.github.io/youtube-dl/index.html

If that is not what you mean, please let me know.

**Comment by boondlai** [comment]
i know about the other add-on but it seemed complicated to me. i don't need to download original media. youtube2anki did the job instantly but i wish i can choose to cut the transcript to make cards (that is choose group of sentences in the transcript for a card) and the addon would play the corresponding audio/video.

**Comment by dobladov** [comment]
I was thinking to add a sentence selector for the users that use the automatic import, at the moment the only way to do what you want is to download the CSV file and delete those sentences you don't want.

I'll keep this issue open, I think is a good idea to implement it. Thanks

**Comment by boondlai** [comment]
is it possible for the sentence selector to select more than one sentence (that is part of the transcript) and is it possible for the corresponding audio/video in that youtube video to play?

**Comment by rpaaron** [comment]
how about being able to use the transcript from the "Add Translations" page?  This would allow the user to fixup the auto generated subtitles, align and break them up as desired before sending to anki

**Comment by dobladov** [comment]
That is a great idea @rpaaron, it will avoid me to add any logic to modify subtitles, I don't have much free time to implement it now, but I give it some thought.

**Comment by Alex200020** [comment]
Hey man, THANK YOU SOOO MUCH. I really like the extension bu is there any way to select more than one sentence for a card because the time is too short and that's mean going to be many cards. I'd like if is it possible to select more than one sentence for the card. Also, is there any way to make it only audio as well? THANK YOU SOOO MUCH.

**Comment by dobladov** [comment]
@Alex200020 At the moment there's no way to select which text composes a card within the extension, for that I would suggest generating CSV files and do the cleanup in Excel, Google sheets or other tool for editing csv.

> Also, is there any way to make it only audio as well?
Might be possible to hide the video with CSS in the template and use autoplay, I can't find an official way to embed YouTube videos as audio.

**Comment by Alex200020** [comment]
Hey Mate, Thank you for your reply. My question was if is possible to combine a few sentences together for example I want to make the card like 50 seconds instead of 10 seconds. . I wasn't asking for the cleanup the sentence. Thank you :)
